name: Build and Push Workflow

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository name'
        required: true
        type: string
      ref:
        description: 'Git reference'
        required: true
        type: string
      image_name:
        description: 'Docker image name'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo workflow inputs
        run: |
          echo "🚀 Starting build and push workflow"
          echo "Repository: ${{ inputs.repository }}"
          echo "Git ref: ${{ inputs.ref }}"
          echo "Image name: ${{ inputs.image_name }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "GitHub event: ${{ github.event_name }}"
          
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Simulate build step
        run: |
          echo "📦 Building application..."
          echo "Build completed successfully!"
          
      - name: Simulate push step
        run: |
          echo "🐳 Pushing to Docker Hub..."
          echo "Image: ${{ inputs.image_name }}"
          echo "Push completed successfully!"
          
      - name: Summary
        run: |
          echo "✅ Workflow completed successfully"
          echo "Repository: ${{ inputs.repository }}"
          echo "Image: ${{ inputs.image_name }}"